repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: system
        types_or: [ts, tsx, javascript, json, css, markdown]
      - id: eslint
        name: eslint
        entry: npx eslint
        language: system
        types_or: [ts, tsx]
        pass_filenames: false
        args: ['.']
      - id: vitest
        name: vitest
        entry: npm test
        language: system
        pass_filenames: false
